name: update dependencies
on:

  schedule:
    - cron:  '0 0 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: development

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.1'
      - run: bundle update --all && bundle install

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: update
        run: yarn install && yarn upgrade

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: development
          branch: dependency-updates
          delete-branch: true
          title: Dependency Updates
          commit-message: Dependency updates
