name: Node & Ruby dependency updates
on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  automatic-release:
    uses: RockefellerArchiveCenter/.github/.github/workflows/node-ruby-dependencies.yml@base
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}